# Generated by Django 5.2.5 on 2025-08-23 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0004_useractivity_videocall"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivity",
            options={"verbose_name_plural": "User Activities"},
        ),
        migrations.AlterModelOptions(
            name="videocall",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="useractivity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useractivity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="videocall",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("ended", "Ended"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
