# Generated by Django 5.2.5 on 2025-10-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0005_alter_useractivity_options_alter_videocall_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_tier",
            field=models.CharField(
                choices=[
                    ("exact", "Exact Skill Match"),
                    ("subcategory", "Subcategory Match"),
                    ("category", "Category Match"),
                ],
                default="exact",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="teacher_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_matches",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_for_skill",
                to="skills.skill",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("learner", "teacher", "skill", "teacher_skill")},
        ),
    ]
