# Generated by Django 5.2.5 on 2025-10-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0006_match_match_tier_match_teacher_skill_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["learner", "teacher", "match_tier"],
                name="skills_matc_learner_fc4da5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["match_tier", "is_mutual"],
                name="skills_matc_match_t_b18cd1_idx",
            ),
        ),
    ]
