# Generated by Django 5.2.5 on 2025-10-09 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0008_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "ordering": ["-last_seen"],
                "verbose_name_plural": "User Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="userskill",
            options={"ordering": ["skill__name"]},
        ),
        migrations.AlterField(
            model_name="userskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_skills",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
